version: '3'
services:
  neo4j:
    image: neo4j-5.3-enterprise-zulu
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
      - 80:80
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
#      - ./plugins:/plugins
    environment:
      - NEO4J_dbms_security_auth__minimum__password__length=4
      - NEO4J_AUTH=neo4j/test
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_apoc_import_file_enabled=true
